id = config.getBlockId("timberStairsID");
name = "timberStairs";
material = "wood";
creativeTab = "buildingBlocks";
stepSound = "wood";
tickrate = 99999;

displayName[0] = "Thatch Stairs";
hardness[0] = 2.0;
drop[0] = config.getBlockId("timberStairsID");
addToCreative[0] = true;
fireSpreadSpeed[0] = 5;
flammability[0] = 40;
textureFileXP[0] = "thatch_64.png";
textureFileXN[0] = "thatch_64.png";
textureFileYP[0] = "thatch_64.png";
textureFileYN[0] = "thatch_64.png";
textureFileZP[0] = "thatch_64.png";
textureFileZN[0] = "thatch_64.png";