id = config.getBlockId("timberFloweredVinesID");
name = "timberFloweredVines";
material = "wood";
creativeTab = "decorations";
stepSound = "wood";
tickrate = 99999;

displayName[0] = "Flowered Vine Lattice";
hardness[0] = 1.0;
drop[0] = config.getBlockId("timberFloweredVinesID");
addToCreative[0] = true;
fireSpreadSpeed[0] = 5;
flammability[0] = 40;
opacity[0] = 3
textureFileXP[0] = "vine1_64.png";
textureFileXN[0] = "vine1_64.png";
textureFileYP[0] = "vine1_64.png";
textureFileYN[0] = "vine1_64.png";
textureFileZP[0] = "vine1_64.png";
textureFileZN[0] = "vine1_64.png";
