id = config.getBlockId("timberPanesID");
name = "timberPanes";
material = "wood";
creativeTab = "buildingBlocks";
stepSound = "wood";
tickrate = 99999;

displayName[0] = "Paper Pane";
hardness[0] = 1.0;
drop[0] = config.getBlockId("timberPanesID");
addToCreative[0] = true;
fireSpreadSpeed[0] = 5;
flammability[0] = 40;
opacity[0] = 1
textureFileXP[0] = "paperwall_64.png";
textureFileXN[0] = "paperwall_64.png";
textureFileYP[0] = "paperwall_64.png";
textureFileYN[0] = "paperwall_64.png";
textureFileZP[0] = "paperwall_64.png";
textureFileZN[0] = "paperwall_64.png";